### PR TITLE
fix search message

### PR DESCRIPTION
**Pull request by linsui**

### CODE REVIEW

**Comment by XilinJia** [comment]
Thanks for the PR.

**Comment by XilinJia** [comment]
The changes don't appear to work.  I got complaint from Intellij:
Wrong argument count, format string `no_results_for_query` requires `0` but format call supplies `1`

**Comment by linsui** [comment]
I built the apk and it works for me. I do not know why IDE complains.

**Comment by XilinJia** [comment]
Yes, it builds OK. Thanks.

**Pull request merged**
